# Generated by Django 3.2.6 on 2021-09-16 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blogger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('body', models.TextField(max_length=1000)),
                ('is_public', models.BooleanField()),
                ('blogger_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogger.blogger')),
            ],
        ),
    ]
