# Generated by Django 3.2.7 on 2021-09-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('body', models.TextField(max_length=1000)),
                ('is_public', models.BooleanField()),
                ('blogger_username', models.CharField(max_length=128)),
            ],
        ),
    ]
