# Generated by Django 3.2.6 on 2021-09-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
