# Generated by Django 3.2.6 on 2021-09-16 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_public',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
